[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."cron-background"]
  schedule = "*/15 * * * *"
  included_files=["functions/emails/*.liquid"]

[functions."cron"]
  included_files=["functions/emails/*.liquid"]

[functions."submission-created"]
  included_files=["functions/emails/*.liquid"]

[[plugins]]
  package = 'netlify-plugin-contextual-env'