[build]
  publish = "dist"
  command = "yarn build"

[functions]
  include_files = "functions/emails/*"
  directory = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "*"