[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Accept = "*"
    Access-Control-Allow-Headers = "*"
    Content-Type = "application/json"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Origin = "*"
    Access-Control-Max-Age = 8640

[functions."cron-background"]
  schedule = "*/15 * * * *"
  included_files=["functions/emails/*.liquid"]

[functions."cron"]
  included_files=["functions/emails/*.liquid"]

[functions."submission-created"]
  included_files=["functions/emails/*.liquid"]

[[plugins]]
  package = 'netlify-plugin-contextual-env'